# -*- coding: utf-8 -*-
"""compression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ALUENpSz7RMPO9Np9ytTIapTGPGFXFu5
"""

from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

im = Image.open(r'camera.png')
im = im.convert('L')
imarray = np.asarray(im)
m = imarray[0]
n = imarray[1]
print(imarray.shape)
u,s,vt = np.linalg.svd(im)
m2 = np.dot(np.dot(u, np.diag(s)), vt)

rank = np.linalg.matrix_rank(im)

k = 226
uk = u[:, :k]
sk = s[:k]
vkt = vt[:k, :]
mk = np.dot(np.dot(uk, np.diag(sk)), vkt)

plt.imshow(Image.fromarray(mk))
plt.savefig("im2.png")
plt.title('k = {}'.format(k))
plt.show()

info = []
sum = 0
for k in range(226):
  sum += s[k]
  info.append(sum)

memory = []
for k in range(226):
  memory.append(k * (226 + 226 + 1))

plt.figure()
plt.plot(s)
plt.title('Singular')
plt.figure()
plt.plot(memory)
plt.title('Memory')
plt.figure()
plt.plot(info)
plt.title('Information')

plt.show()